#BACKPROP_MODIFIER = 'guided'
#UNET_NAME = f'UNet_RGB_SAL_MAP_{BACKPROP_MODIFIER.upper()}'
UNET_NAME = f'UNet_RGB'
DATASET_NAME = 'icoseg/subset_80'
EXPERIMENT_NAME = f'{DATASET_NAME}/{UNET_NAME}'

PRED_THR = 0.5
INPUT_SHAPE = (512, 512, 3)
SALIENCY_INPUT_SHAPE = (224, 224, 3)
BATCH_SIZE = 1
NUM_EPOCHS = 20